apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:   # This was the issue
    app: backend
spec:
  selector:
    app: backend    # select pods with this label
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080