apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:   # This was the issue
    app: frontend
spec:
  selector:
    app: frontend    # select pods with this label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer