apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File /fluent-bit/etc/parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    # -------------------------
    # LOGS INPUT
    # -------------------------
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /fluent-bit/tail.db
        Mem_Buf_Limit     7MB
        Refresh_Interval  5
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
        Keep_Log            On
        K8S-Logging.Parser  On


    # -------------------------
    # METRICS INPUTS
    # -------------------------
    [INPUT]
        Name cpu
        Tag metrics.cpu
        Interval_Sec 5

    [INPUT]
        Name mem
        Tag metrics.mem
        Interval_Sec 5

    [INPUT]
        Name netif
        Tag metrics.net
        Interface eth0
        Interval_Sec 5

    # -------------------------
    # LOG PARSING
    # -------------------------
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_URL https://kubernetes.default.svc:443
        Merge_Log On
        Keep_Log On
        K8S-Logging.Parser On

    # -------------------------
    # METRICS NORMALIZATION
    # -------------------------
    [FILTER]
        Name lua
        Match metrics.*
        Script /fluent-bit/etc/metrics-normalizer.lua
        Call normalize_metrics

    # -------------------------
    # CloudWatch Logs Output
    # -------------------------
    [OUTPUT]
        Name                  cloudwatch_logs
        Match                 *
        region                ap-south-1
        log_group_name        /aks/aiops-platform
        log_stream_prefix     aks-
        auto_create_group     true
        auto_retry_requests   On

    # -------------------------
    # Kinesis Streams Output
    # -------------------------
    [OUTPUT]
        Name                  kinesis_streams
        Match                 *
        region                ap-south-1
        stream                fluentbit-metrics
        auto_retry_requests   On

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: default

      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.0
          ports:
            - containerPort: 2020
              name: http

          # AWS credentials injected from Secret
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: fluentbit-aws-credentials
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fluentbit-aws-credentials
                  key: AWS_SECRET_ACCESS_KEY

          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/lib/docker/containers

      volumes:
        - name: config
          configMap:
            name: fluent-bit-config

        - name: varlog
          hostPath:
            path: /var/log

        - name: containers
          hostPath:
            path: /var/lib/docker/containers
