apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:

  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File /fluent-bit/etc/parsers.conf

    ##########################################
    # LOG INPUT
    ##########################################
    [INPUT]
        Name tail
        Tag logs.*
        Path /var/log/containers/*.log
        Parser docker

    [FILTER]
        Name kubernetes
        Match logs.*
        Merge_Log On
        Keep_Log On

    ##########################################
    # METRICS INPUT (Node Exporter)
    ##########################################
    [INPUT]
        Name node_exporter_metrics
        Tag metrics.node
        Host localhost
        Port 9100
        Interval_Sec 5

    ##########################################
    # METRIC NORMALIZER (LUA)
    ##########################################
    [FILTER]
        Name lua
        Match metrics.node
        Script /fluent-bit/etc/metrics-normalizer.lua
        Call normalize

    ##########################################
    # OUTPUTS
    ##########################################

    # Logs → CloudWatch
    [OUTPUT]
        Name cloudwatch_logs
        Match logs.*
        region ap-south-1
        log_group_name /aks/aiops-platform
        auto_create_group On

    # Metrics → Kinesis
    [OUTPUT]
        Name kinesis_streams
        Match metrics.*
        region ap-south-1
        stream fluentbit-metrics
        auto_retry_requests On

  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On

  metrics-normalizer.lua: |
    function normalize(tag, ts, record)
        local out = {}
        local name = record["name"]

        if name == "node_cpu_seconds_total" then
            out["metric_type"] = "cpu"
            out["value"] = record["value"] or 0

        elseif name == "node_memory_Active_bytes" then
            out["metric_type"] = "memory"
            out["value"] = record["value"] or 0

        elseif name == "node_network_transmit_bytes_total" then
            out["metric_type"] = "traffic"
            out["value"] = record["value"] or 0

        else
            return 0, ts, record
        end

        out["timestamp"] = os.date("!%Y-%m-%dT%H:%M:%SZ", ts)
        out["service"] = "aks"
        out["node"] = record["instance"] or "aks-node"

        return 1, ts, out
    end
