apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  selector:
    app.kubernetes.io/name: prometheus-node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  type: ClusterIP