apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod
spec:
  containers:
  - name: stress-container
    image: polinux/stress:latest
    command: ["stress"]
    args: ["--cpu", "4", "--timeout", "600s"]
    resources:
      limits:
        cpu: "1000m"
      requests:
        cpu: "500m"