apiVersion: batch/v1
kind: Job
metadata:
  name: mem-leak-job
spec:
  template:
    spec:
      containers:
      - name: memory-leak
        image: polinux/stress
        args:
          - "--vm"
          - "1"
          - "--vm-bytes"
          - "900M"
          - "--vm-hang"
          - "1"
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "800Mi"
      restartPolicy: Never
  backoffLimit: 0
